#pragma once

#define CPU_INTERRUPT_DIVIDED_BY_0 0
#define CPU_INTERRUPT_DEBUG_EXCEPTION 1
#define CPU_INTERRUPT_NON_MASKABLE_INTERRUPT 2
#define CPU_INTERRUPT_BREAK_POINT 3
#define CPU_INTERRUPT_INTO_DETECTED_OVERFLOW 4
#define CPU_INTERRUPT_OUT_OF_BOUNDS_EXCEPTION 5
#define CPU_INTERRUPT_INVALID_OPCODE_EXCEPTION 6
#define CPU_INTERRUPT_NO_COPROCESSOR_EXCEPTION 7
#define CPU_INTERRUPT_DOUBLE_FAULT 8 // ERROR_CODE
#define CPU_INTERRUPT_COPROCESSOR_SEGMENT_OVERRUN 9
#define CPU_INTERRUPT_INVALID_TSS 10 // ERROR_CODE
#define CPU_INTERRUPT_SEGMENT_NOT_PRESENT 11 // ERROR_CODE
#define CPU_INTERRUPT_STACK_FAULT 12 // ERROR_CODE
#define CPU_INTERRUPT_GENERAL_PROTECTION_FAULT 13 // ERROR_CODE
#define CPU_INTERRUPT_PAGE_FAULT 14 // ERROR_CODE
#define CPU_INTERRUPT_UNKOWN_INTERRUPT_EXCEPTION 15
#define CPU_INTERRUPT_COPROCESSOR_FAULT 16
#define CPU_INTERRUPT_ALIGNMENT_CHECK_EXCEPTION 17 // ERROR_CODE
#define CPU_INTERRUPT_MACHINE_CHECK_EXCEPTION 18
#define CPU_INTERRUPT_SIMD_FLOATING_POINT_EXCEPTION 19
#define CPU_INTERRUPT_VIRTUALIZATION_EXCEPTION 20
#define CPU_INTERRUPT_CONTROL_PROTECTION_EXCEPTION 21 // ERROR_CODE
#define CPU_INTERRUPT_HYPERVISOR_INJECTION_EXCEPTION 28
#define CPU_INTERRUPT_VMM_COMMUNICATION_EXCEPTION 29 // ERROR_CODE
#define CPU_INTERRUPT_SECURITY_EXCEPTION 30 // ERROR_CODE
